FROM ghcr.io/open-webui/open-webui:main

# Expose the port that the application uses
EXPOSE 8080

# Set environment variables
# Railway requires the PORT environment variable to be set
ENV PORT=8080
ENV ENABLE_OLLAMA_API=false
ENV ENABLE_IMAGE_GENERATION=false
ENV ENABLE_RAG_WEB_SEARCH=false
